### ISSUE TITLE
Error when generating configuration after preparing dataset

### ISSUE THREAD

**Issue by CtrlAltDefeat55** [JarodMica/ai-voice-cloning#1]
I'm encountering an "Empty dataset" exception in the voice cloning application after following the steps outlined in the installation video. This problem comes up when I switch to the "Generate Configuration" section and Validate Training Configuration.

Traceback (most recent call last):
  File "E:\AI_Apps\ai-voice-cloning\runtime\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI_Apps\ai-voice-cloning\runtime\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\AI_Apps\ai-voice-cloning\runtime\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Ky\AppData\Roaming\Python\Python39\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Ky\AppData\Roaming\Python\Python39\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Ky\AppData\Roaming\Python\Python39\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AI_Apps\ai-voice-cloning\src\webui.py", line 272, in optimize_training_settings_proxy
    settings, messages = optimize_training_settings(**kwargs)
  File "E:\AI_Apps\ai-voice-cloning\src\utils.py", line 2809, in optimize_training_settings
    raise Exception("Empty dataset.")
Exception: Empty dataset.

Environment:
Operating System: Windows
Hardware: NVIDIA GeForce RTX 4090, Intel Core i7-12700KF, 64 GB DDR4 RAM

Let me know if any other details on this bug would be helpful! Thanks for looking into resolving this.

**Comment by JarodMica** [comment]
Sorry on the delayed response here. Have you tried this on other voice datasets? If you could verify whether this happens when trying to use fresh datasets, that may help.

**Comment by CtrlAltDefeat55** [comment]
I did try it on another data set and had the same issue? I used a fresh dataset this time.

**Comment by Shawn0008** [comment]
Hi @CtrlAltDefeat55, I had the same issue, for some reason in the voice folder under the training folder my validation.txt was actually named train.txt, just swapped the names and then it worked for me, hope it helps!

**Comment by JarodMica** [comment]
> Hi @CtrlAltDefeat55, I had the same issue, for some reason in the voice folder under the training folder my validation.txt was actually named train.txt, just swapped the names and then it worked for me, hope it helps!

This should work, we just had this work for someone in the discord as well. Why it puts all of the text onto validation instead of train is weird, but copy/pasting the contents or renaming them can allow for training to continue.

**Comment by CtrlAltDefeat55** [comment]
Thank you! That worked. Sorry, I havn't been on for the holidays.
