### ISSUE TITLE
Attempting to transcribe audio and prepare a dataset results in an error.

### ISSUE THREAD

**Issue by hax4dazy** [JarodMica/ai-voice-cloning#108]
I've converted my dataset into WAV files and put them in a folder in `ai-voice-cloning-3.0\voices` but upon it trying to segment the audio it fails and errors out with the error `RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous`

I have looked though the issues and there seems to be one other person facing this issue but they've gotten past the dataset creation part.

Here's a copy of the logs
<details>
    <summary>
        Log Paste:
    </summary>
    <code>Text length too long (200 < 1362), using segments: F0001.wav
Audio not segmented, segmenting: F0001.wav
Sliced segments: 1 => 17.
Text length too long (200 < 934), using segments: F0002.wav
Audio not segmented, segmenting: F0002.wav
Sliced segments: 1 => 15.
Text length too long (200 < 2290), using segments: FM001.wav
Audio not segmented, segmenting: FM001.wav
Sliced segments: 1 => 30.
Text length too long (200 < 1516), using segments: M0001.wav
Audio not segmented, segmenting: M0001.wav
Sliced segments: 1 => 19.
Text length too long (200 < 1885), using segments: M0002.wav
Audio not segmented, segmenting: M0002.wav
Sliced segments: 1 => 41.
Text length too long (200 < 1571), using segments: M0003.wav
Audio not segmented, segmenting: M0003.wav
Sliced segments: 1 => 25.
Text length too long (200 < 1224), using segments: M0004.wav
Audio not segmented, segmenting: M0004.wav
Sliced segments: 1 => 22.
Text length too long (200 < 2392), using segments: M0005.wav
Audio not segmented, segmenting: M0005.wav
Sliced segments: 1 => 35.
Text length too long (200 < 3006), using segments: M0006.wav
Audio not segmented, segmenting: M0006.wav
Sliced segments: 1 => 53.
Text length too long (200 < 3306), using segments: M0007.wav
Audio not segmented, segmenting: M0007.wav
Sliced segments: 1 => 70.
Text length too long (200 < 2621), using segments: M0008.wav
Audio not segmented, segmenting: M0008.wav
Sliced segments: 1 => 38.
Text length too long (200 < 493), using segments: M0009.wav
Audio not segmented, segmenting: M0009.wav
Sliced segments: 1 => 10.
Text length too long (200 < 1882), using segments: M0010.wav
Audio not segmented, segmenting: M0010.wav
Sliced segments: 1 => 32.
Text length too long (200 < 1248), using segments: M0011.wav
Audio not segmented, segmenting: M0011.wav
Sliced segments: 1 => 16.
Text length too long (200 < 2305), using segments: M0012.wav
Audio not segmented, segmenting: M0012.wav
Sliced segments: 1 => 48.
Text length too long (200 < 1749), using segments: M0013.wav
Audio not segmented, segmenting: M0013.wav
Traceback (most recent call last):
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\src\webui.py", line 291, in prepare_all_datasets
    message = prepare_dataset(voice, use_segments=slice_audio, text_length=validation_text_length,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\src\utils.py", line 2644, in prepare_dataset
    message = slice_dataset( voice, results=tmp )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\src\utils.py", line 2440, in slice_dataset
    sliced, _ = resample( sliced, sample_rate, TARGET_SAMPLE_RATE )
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\src\utils.py", line 362, in resample
    return RESAMPLERS[key]( waveform ), output_rate
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\torchaudio\transforms\_transforms.py", line 979, in forward
    return _apply_sinc_resample_kernel(waveform, self.orig_freq, self.new_freq, self.gcd, self.kernel, self.width)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\torchaudio\functional\functional.py", line 1462, in _apply_sinc_resample_kernel
    waveform = waveform.view(-1, shape[-1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
</code>
</details>

**Comment by hax4dazy** [comment]
I've tried again with a different dataset and it appears that i still get the same error.

**Comment by misraj-ah** [comment]
Hello, I'm getting the same error of you when I'm trying to train the model, Have you managed to solve the problem ? if so could you please help me to solve it ?
