### ISSUE TITLE
Can't run start.bat

### ISSUE THREAD

**Issue by KvasRoman** [JarodMica/ai-voice-cloning#129]
I receive this error log on start.bat open:
```
call .\venv\Scripts\activate.bat
Traceback (most recent call last):
  File "D:\programs\cloned_projects_git\ai-voice-cloning\src\main.py", line 23, in <module>
    from utils import *
  File "D:\programs\cloned_projects_git\ai-voice-cloning\src\utils.py", line 48, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\rvc_pipe\rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "D:\programs\cloned_projects_git\ai-voice-cloning\rvc\infer\modules\vc\modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "D:\programs\cloned_projects_git\ai-voice-cloning\rvc\infer\modules\vc\utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\fairseq\__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\fairseq\dataclass\initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\hydra\utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 9, in <module>
    from omegaconf import OmegaConf, SCMode
ImportError: cannot import name 'SCMode' from 'omegaconf' (D:\programs\cloned_projects_git\ai-voice-cloning\venv\Lib\site-packages\omegaconf\__init__.py)
```
During the installation via start-cuda.bat I have this error message:
```
pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hydra-core 1.3.2 requires omegaconf<2.4,>=2.2, but you have omegaconf 2.0.0 which is incompatible.
pyannote-audio 3.1.1 requires omegaconf<3.0,>=2.1, but you have omegaconf 2.0.0 which is incompatible.
```
My hardware:
GPU: GeForce RTX 3090 Ti
CPU: AMD Ryzen 5 7500 6-Core Processor
OS: Windows 10 Pro (x64)

**Comment by notomato1** [comment]
Same here

**Comment by BRLTS** [comment]
Already tried that, but It's not working
