### ISSUE TITLE
docker error (linux)

### ISSUE THREAD

**Issue by sanihaq** [JarodMica/ai-voice-cloning#130]
Traceback (most recent call last):
  File "/home/user/ai-voice-cloning/./src/main.py", line 23, in <module>
    from utils import *
  File "/home/user/ai-voice-cloning/src/utils.py", line 48, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "/home/user/miniconda/lib/python3.11/site-packages/rvc_pipe/rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "/home/user/ai-voice-cloning/rvc/infer/modules/vc/modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "/home/user/ai-voice-cloning/rvc/infer/modules/vc/utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "/home/user/miniconda/lib/python3.11/site-packages/fairseq/__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "/home/user/miniconda/lib/python3.11/site-packages/fairseq/dataclass/initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 9, in <module>
    from omegaconf import OmegaConf, SCMode
ImportError: cannot import name 'SCMode' from 'omegaconf' (/home/user/miniconda/lib/python3.11/site-packages/omegaconf/__init__.py)
Press Cntrl-C to quit or application will restart... (5s)
Traceback (most recent call last):
  File "/home/user/ai-voice-cloning/./src/main.py", line 23, in <module>
    from utils import *
  File "/home/user/ai-voice-cloning/src/utils.py", line 48, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "/home/user/miniconda/lib/python3.11/site-packages/rvc_pipe/rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "/home/user/ai-voice-cloning/rvc/infer/modules/vc/modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "/home/user/ai-voice-cloning/rvc/infer/modules/vc/utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "/home/user/miniconda/lib/python3.11/site-packages/fairseq/__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "/home/user/miniconda/lib/python3.11/site-packages/fairseq/dataclass/initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 9, in <module>
    from omegaconf import OmegaConf, SCMode
ImportError: cannot import name 'SCMode' from 'omegaconf' (/home/user/miniconda/lib/python3.11/site-packages/omegaconf/__init__.py)
Press Cntrl-C to quit or application will restart... (5s)
Traceback (most recent call last):
  File "/home/user/ai-voice-cloning/./src/main.py", line 23, in <module>
    from utils import *
  File "/home/user/ai-voice-cloning/src/utils.py", line 48, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "/home/user/miniconda/lib/python3.11/site-packages/rvc_pipe/rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "/home/user/ai-voice-cloning/rvc/infer/modules/vc/modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "/home/user/ai-voice-cloning/rvc/infer/modules/vc/utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "/home/user/miniconda/lib/python3.11/site-packages/fairseq/__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "/home/user/miniconda/lib/python3.11/site-packages/fairseq/dataclass/initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/home/user/miniconda/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 9, in <module>
    from omegaconf import OmegaConf, SCMode
ImportError: cannot import name 'SCMode' from 'omegaconf' (/home/user/miniconda/lib/python3.11/site-packages/omegaconf/__init__.py)
Press Cntrl-C to quit or application will restart... (5s)

**Comment by ctothe** [comment]
Having the same issue. I noticed there is no 'miniconda' dir. Theres is a 'miniconda3', though.
