### ISSUE TITLE
ImportError: cannot import name 'SCMode' from 'omegaconf'

### ISSUE THREAD

**Issue by codeolder** [JarodMica/ai-voice-cloning#136]
C:\Users\PC\Downloads\ai-voice-cloning>call .\venv\Scripts\activate.bat
Traceback (most recent call last):
  File "C:\Users\PC\Downloads\ai-voice-cloning\src\main.py", line 23, in <module>
    from utils import *
  File "C:\Users\PC\Downloads\ai-voice-cloning\src\utils.py", line 48, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\rvc_pipe\rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "C:\Users\PC\Downloads\ai-voice-cloning\rvc\infer\modules\vc\modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "C:\Users\PC\Downloads\ai-voice-cloning\rvc\infer\modules\vc\utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\fairseq\__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\fairseq\dataclass\initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\hydra\utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 9, in <module>
    from omegaconf import OmegaConf, SCMode
ImportError: cannot import name 'SCMode' from 'omegaconf' (C:\Users\PC\Downloads\ai-voice-cloning\venv\Lib\site-packages\omegaconf\__init__.py)
Press any key to continue . . .

**Comment by mducng697** [comment]
same here

**Comment by 2kpr** [comment]
I got mine working using:
pip install nemo_toolkit==1.0.0

I used the setup-cuda.sh from https://github.com/JarodMica/ai-voice-cloning/pull/77 on debian 12, also had to remove the '--remote' per https://github.com/JarodMica/ai-voice-cloning/issues/120#issuecomment-2159225523

**Comment by hogansung** [comment]
Changing `omegaconf<=2.1` to `omegaconf<=2.3` and rerunning `./setup-docker.sh`  resolved the issue for me.

**Comment by RobinManoli** [comment]
There are a bunch of conflicts coming up for me during the pip installation: omegaconf, librosa and pydantic keep coming up, and the wrong versions are somehow being installed although requirements.txt have correct versions for:
pydantic==2.6.4
librosa==0.9.1

and with @hogansung's fix:
omegaconf<=2.3y

With the fix it worked for me.

I thought it got stuck at "Loaded TTS, ready for generation", but this was actually the time to open http://127.0.0.1:7860/ in the browser.
