### ISSUE TITLE
KeyError: 'rvc_model'

### ISSUE THREAD

**Issue by FatheredPuma81** [JarodMica/ai-voice-cloning#137]
This is what I get when I try to use RVC.
```
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\src\webui.py", line 134, in generate_proxy
    raise e
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\src\webui.py", line 128, in generate_proxy
    sample, outputs, stats = generate(**kwargs)
                             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\src\utils.py", line 366, in generate
    return generate_tortoise(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ai-voice-cloning-3.0\src\utils.py", line 1375, in generate_tortoise
    rvc_model_path = os.path.join("models", "rvc_models", rvc_settings['rvc_model'])
                                                          ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'rvc_model'
```

**Comment by fygarcia** [comment]
Same thing here

**Comment by przanowo** [comment]
yepp same here.

**Comment by Suresh-Kumar-sudo** [comment]
same here too

**Comment by Azrox01** [comment]
uncheck the "Run the outputted audio through RVC" in "Show Experimental Settings" unless you have a RVC Voice Model.

**Comment by FatheredPuma81** [comment]
> uncheck the "Run the outputted audio through RVC" in "Show Experimental Settings" unless you have a RVC Voice Model.

Lmfao

**Comment by Azrox01** [comment]
well I don't know any other way... let me know if you find it out.

**Comment by RookieKiwi** [comment]
Same issue here, tried a fresh installation with the same result. Windows 11 - 4060 - got a pre-trained voice from a friend with RVC, get the below error message.

`
[2024-08-22 10:59:36,371] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-22 10:59:36,589] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
2024-08-22 10:59:37 | INFO | rvc.configs.config | Found GPU NVIDIA GeForce RTX 4060
Whisper detected
C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\components\dropdown.py:179: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py:858: UserWarning: Expected 1 arguments for function <function update_voices at 0x000001D30B1BF600>, received 0.
  warnings.warn(
C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py:862: UserWarning: Expected at least 1 arguments for function <function update_voices at 0x000001D30B1BF600>, received 0.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
2024-08-22 10:59:39 | INFO | httpx | HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
2024-08-22 10:59:39 | INFO | httpx | HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
Loading TorToiSe... (AR: ./training/Jameswhyte/finetune/models/500_gpt.pth, diffusion: ./models/tortoise/diffusion_decoder.pth, vocoder: bigvgan_24khz_100band)
Hardware acceleration found: cuda
use_deepspeed api_debug False
2024-08-22 10:59:39 | INFO | httpx | HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
IMPORTANT: You are using gradio version 4.22.0, however version 4.29.0 is available, please upgrade.
--------
C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loading tokenizer JSON: ./modules/tortoise-tts/tortoise/data/tokenizer.json
Loaded tokenizer
Loading autoregressive model: ./training/Jameswhyte/finetune/models/500_gpt.pth
Loaded autoregressive model
Loaded diffusion model
Loading vocoder model: bigvgan_24khz_100band
Loading vocoder model: bigvgan_24khz_100band.pth
Removing weight norm...
Loaded vocoder model
Loaded TTS, ready for generation.
[1/1] Generating line: this is my prompt yo
Loading voice: Jameswhyte with model 57e6552c
Loading voice: Jameswhyte
Reading from latent: ./voices/Jameswhyte//cond_latents_57e6552c.pth
{'temperature': 0.2, 'top_p': 0.8, 'diffusion_temperature': 1.0, 'length_penalty': 1.0, 'repetition_penalty': 2.0, 'cond_free_k': 2.0, 'num_autoregressive_samples': 16, 'sample_batch_size': 4, 'diffusion_iterations': 30, 'voice_samples': None, 'conditioning_latents': (tensor([[-2.0333, -0.2530, -0.1508,  ...,  0.2301, -2.5215, -0.6159]]), tensor([[-1.0059, -1.2639, -0.4111,  ..., -0.0491, -0.0200,  0.1237]])), 'use_deterministic_seed': None, 'return_deterministic_state': True, 'k': 1, 'diffusion_sampler': 'DDIM', 'breathing_room': 8, 'half_p': False, 'cond_free': True, 'cvvp_amount': 0, 'autoregressive_model': './training/Jameswhyte/finetune/models/500_gpt.pth', 'diffusion_model': './models/tortoise/diffusion_decoder.pth', 'tokenizer_json': './modules/tortoise-tts/tortoise/data/tokenizer.json'}
Generating line took 16.873845100402832 seconds
C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\src\utils.py:355: UserWarning: "kaiser_window" resampling method name is being deprecated and replaced by "sinc_interp_kaiser" in the next release. The default behavior remains unchanged.
  RESAMPLERS[key] = torchaudio.transforms.Resample(
Traceback (most recent call last):
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\src\webui.py", line 134, in generate_proxy
    raise e
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\src\webui.py", line 128, in generate_proxy
    sample, outputs, stats = generate(**kwargs)
                             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\src\utils.py", line 368, in generate
    return generate_tortoise(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckrewt\Desktop\TTS\ai-voice-cloning-3.0\src\utils.py", line 1378, in generate_tortoise
    rvc_model_path = os.path.join("models", "rvc_models", rvc_settings['rvc_model'])
                                                          ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'rvc_model'

`

**Comment by JarodMica** [comment]
Hey guys,

Sorry for the inactivity here, but I looked into this and it looks like a certain behavior which I thought existed was never implemented.

Inside of the base folder, inside of configs, try creating a file called ```rvc.json```

The path to it should look like this:
```
./config/rvc.json
```

Then, inside of the file, paste and save:
```
{
    'rvc_model': '',
    'f0_up_key': 0,
    'file_index': '',
    'index_rate': 0,
    'filter_radius': 3,
    'resample_sr': 48000,
    'rms_mix_rate': 0.25,
    'protect': 0.33,
}
```

I'll try to get some patches out for this repo, but no exact timeline for the turnaround

**Comment by RookieKiwi** [comment]
Couple of quoting issues with the above config, changed to below and worked flawlessly thank you!

`{
    "rvc_model": "model.pth",
    "f0_up_key": 0,
    "file_index": "file.index",
    "index_rate": 0,
    "filter_radius": 3,
    "resample_sr": 48000,
    "rms_mix_rate": 0.25,
    "protect": 0.33
}`

**Comment by FatheredPuma81** [comment]
Well now I get a new error so that's progress I guess. 
`[1/1] Generating line: This is a test of RVC implementation.
Loading voice: audible with model d1f79232
Loading voice: audible
Reading from latent: ./voices/audible//cond_latents_d1f79232.pth
{'temperature': 0.8, 'top_p': 0.8, 'diffusion_temperature': 1.0, 'length_penalty': 1.0, 'repetition_penalty': 2.0, 'cond_free_k': 2.0, 'num_autoregressive_samples': 2, 'sample_batch_size': 2, 'diffusion_iterations': 30, 'voice_samples': None, 'conditioning_latents': (tensor([[ 1.5287,  3.8802,  0.7670,  ..., -1.9555, -1.3124, -2.1340]]), tensor([[-0.8292, -0.9843, -1.0264,  ..., -0.0289,  0.0639,  0.3538]])), 'use_deterministic_seed': None, 'return_deterministic_state': True, 'k': 1, 'diffusion_sampler': 'DDIM', 'breathing_room': 8, 'half_p': False, 'cond_free': False, 'cvvp_amount': 0, 'autoregressive_model': './models/tortoise/autoregressive.pth', 'diffusion_model': './models/tortoise/diffusion_decoder.pth', 'tokenizer_json': './modules/tortoise-tts/tortoise/data/tokenizer.json'}
Generating line took 5.16300368309021 seconds
C:\Program Files (x86)\ai-voice-cloning-3.0\src\utils.py:353: UserWarning: "kaiser_window" resampling method name is being deprecated and replaced by "sinc_interp_kaiser" in the next release. The default behavior remains unchanged.
  RESAMPLERS[key] = torchaudio.transforms.Resample(
models\rvc_models\model.pth
Traceback (most recent call last):
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\webui.py", line 134, in generate_proxy
    raise e
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\webui.py", line 128, in generate_proxy
    sample, outputs, stats = generate(**kwargs)
                             ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\utils.py", line 366, in generate
    return generate_tortoise(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\utils.py", line 1378, in generate_tortoise
    rvc_out_path = rvc_convert(model_path=rvc_model_path,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\rvc_pipe\rvc_infer.py", line 122, in rvc_convert
    vc.get_vc(model_path)
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\rvc\infer\modules\vc\modules.py", line 109, in get_vc
    self.cpt = torch.load(person, map_location="cpu", weights_only=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\ai-voice-cloning-3.0\\models\\rvc_models\\model.pth'`

**Comment by RookieKiwi** [comment]
> Well now I get a new error so that's progress I guess.
> 
> ```
> [1/1] Generating line: This is a test of RVC implementation.
> Loading voice: audible with model d1f79232
> Loading voice: audible
> Reading from latent: ./voices/audible//cond_latents_d1f79232.pth
> {'temperature': 0.8, 'top_p': 0.8, 'diffusion_temperature': 1.0, 'length_penalty': 1.0, 'repetition_penalty': 2.0, 'cond_free_k': 2.0, 'num_autoregressive_samples': 2, 'sample_batch_size': 2, 'diffusion_iterations': 30, 'voice_samples': None, 'conditioning_latents': (tensor([[ 1.5287,  3.8802,  0.7670,  ..., -1.9555, -1.3124, -2.1340]]), tensor([[-0.8292, -0.9843, -1.0264,  ..., -0.0289,  0.0639,  0.3538]])), 'use_deterministic_seed': None, 'return_deterministic_state': True, 'k': 1, 'diffusion_sampler': 'DDIM', 'breathing_room': 8, 'half_p': False, 'cond_free': False, 'cvvp_amount': 0, 'autoregressive_model': './models/tortoise/autoregressive.pth', 'diffusion_model': './models/tortoise/diffusion_decoder.pth', 'tokenizer_json': './modules/tortoise-tts/tortoise/data/tokenizer.json'}
> Generating line took 5.16300368309021 seconds
> C:\Program Files (x86)\ai-voice-cloning-3.0\src\utils.py:353: UserWarning: "kaiser_window" resampling method name is being deprecated and replaced by "sinc_interp_kaiser" in the next release. The default behavior remains unchanged.
>   RESAMPLERS[key] =  torchaudio.transforms.Resample(
> models\rvc_models\model.pth
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\queueing.py", line 501, in call_prediction
>     output = await route_utils.call_process_api(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
>     output = await app.get_blocks().process_api(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1710, in process_api
>     result = await self.call_function(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\blocks.py", line 1250, in call_function
>     prediction = await anyio.to_thread.run_sync(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
>     return await future
>            ^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
>     result = context.run(func, *args)
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
>     response = f(*args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py", line 693, in wrapper
>     response = f(*args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\webui.py", line 134, in generate_proxy
>     raise e
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\webui.py", line 128, in generate_proxy
>     sample, outputs, stats = generate(**kwargs)
>                              ^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\utils.py", line 366, in generate
>     return generate_tortoise(**kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\src\utils.py", line 1378, in generate_tortoise
>     rvc_out_path = rvc_convert(model_path=rvc_model_path,
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\rvc_pipe\rvc_infer.py", line 122, in rvc_convert
>     vc.get_vc(model_path)
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\rvc\infer\modules\vc\modules.py", line 109, in get_vc
>     self.cpt = torch.load(person, map_location="cpu", weights_only=True)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\serialization.py", line 998, in load
>     with _open_file_like(f, 'rb') as opened_file:
>          ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\serialization.py", line 426, in __init__
>     super().__init__(open(name, mode))
>                      ^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\ai-voice-cloning-3.0\\models\\rvc_models\\model.pth'
> ```

rename model.pth to your model and file.index to your index file in the config and your away

**Comment by FatheredPuma81** [comment]
> rename model.pth to your model and file.index to your index file in the config and your away

Yea turns out you can't just copy the model path into it and you also have to press the Refresh button a lot of times (or it takes forever to scan that folder). Finally works now.

**Comment by JarodMica** [comment]
Yeah, mb my dudes, it was supposed to have a "default" option that gets created if that file was not present, but looks like I never made the logic for that. Thanks for waiting 🙏

**Comment by RookieKiwi** [comment]
> Yeah, mb my dudes, it was supposed to have a "default" option that gets created if that file was not present, but looks like I never made the logic for that. Thanks for waiting 🙏

thanks for all your hard work man appreciate it, love the content.
