### ISSUE TITLE
Docker not working.

### ISSUE THREAD

**Issue by blastbeng** [JarodMica/ai-voice-cloning#153]
I am trying to build and run the docker image using both ./setup-docker.sh and start-docker.sh

I have everything working in my ubuntu setup (cuda drivers, etc...)) but i have this error:

```
blast@BLASTPC:/opt/projects/ai-voice-cloning$ ./start-docker.sh

==========
== CUDA ==
==========

CUDA Version 12.2.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Traceback (most recent call last):
  File "/home/user/ai-voice-cloning/./src/main.py", line 23, in <module>
    from utils import *
  File "/home/user/ai-voice-cloning/src/utils.py", line 30, in <module>
    import torchaudio
  File "/home/user/miniconda/lib/python3.11/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/home/user/miniconda/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "/home/user/miniconda/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/user/miniconda/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c105Error4whatEv
Press Cntrl-C to quit or application will restart... (5s)
```

**Comment by jeff-bennett** [comment]
I get the same error running on linux without docker with python 3.10 or  3.11.

**Comment by Mr-Anwaar** [comment]
update the Docker as its not working , its a Package mis-matching issue

**Comment by Mr-Anwaar** [comment]
@JarodMica please, check the Packages mis-matching in docker as it is causing error and not running,  trying from almost three days .

**Comment by TheDarkTrumpet** [comment]
I got the same issue.  Same as I did with the self-install.  Something that could help is when I was installing manually on Debian, I got the following:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.4.0+cu118 requires torch==2.4.0, but you have torch 2.3.1 which is incompatible.
torchvision 0.19.0+cu118 requires torch==2.4.0, but you have torch 2.3.1 which is incompatible.
```

This was at the last step (installing the root requirements)

**Comment by Likkkez** [comment]
Same problem here. Tried in docker first, then installed without docker and still same error:
```
[Training] [2024-09-03T01:04:56.385658]     torch.ops.load_library(path)
[Training] [2024-09-03T01:04:56.386337]   File "/media/manjaro/NVME_2tb/NeuralNetworks/ai-voice-cloning/venv/lib/python3.11/site-packages/torch/_ops.py", line 1032, in load_library
[Training] [2024-09-03T01:04:56.387017]     ctypes.CDLL(path)
[Training] [2024-09-03T01:04:56.387690]   File "/home/manjaro/.conda/envs/TTS/lib/python3.11/ctypes/__init__.py", line 376, in __init__
[Training] [2024-09-03T01:04:56.388380]     self._handle = _dlopen(self._name, mode)
[Training] [2024-09-03T01:04:56.389060]                    ^^^^^^^^^^^^^^^^^^^^^^^^^
[Training] [2024-09-03T01:04:56.389736] OSError: /media/manjaro/NVME_2tb/NeuralNetworks/ai-voice-cloning/venv/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c105Error4whatEv

```

**Comment by TheDarkTrumpet** [comment]
If you went back to trying from source (like I did too).  I found that the submodules wanted torch at specific versions, while the webui also wanted it at other versions.  It's not the only issue, but maybe you'll get past the others.  Try running and mirroring the following, specifically torch, torchaudio, and torchvision.

```
❯ pip list | grep -i 'torch'
g-mlp-pytorch                0.1.5
gsa-pytorch                  0.2.2
pytorch-fid                  0.3.0
pytorch-lightning            2.4.0
pytorch-metric-learning      2.6.0
pytorch_ssim                 0.1
rotary-embedding-torch       0.4.0
torch                        2.3.1
torch-audiomentations        0.11.1
torch-pitch-shift            1.2.4
torchaudio                   2.3.1
torchcrepe                   0.0.22
torchlibrosa                 0.1.0
torchmetrics                 1.4.1
torchvision                  0.18.1
vector-quantize-pytorch      1.16.2
```

Another thing I found that shot myself in the foot was the Python version.  This project, I believe, says to use 3.11.  The subprojects have some real pickiness with the Python version.  While I did get it working with 3.11.9, it wasn't good - way too much work.  I think trying to settle with `3.10.13` (or .14, but that had issues building in pyenv)

**Comment by maepopi** [comment]
I have the same problem unfortunately...

**Comment by antjpcdrogas** [comment]
I was able to bypass this error with:
pip3 install -U torch torchaudio

**Comment by labay-adam** [comment]
With luck, https://github.com/JarodMica/ai-voice-cloning/pull/179 should handle the situation.
