### ISSUE TITLE
Error with Pydantic and startlette request on docker ?

### ISSUE THREAD

**Issue by maepopi** [JarodMica/ai-voice-cloning#162]
Hey there,

I've just updated the repo and rebuild the docker using setup-docker, but when I launch the start-docker and try to open the server I have errors everywhere in Gradio, and the console shows this 

`
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/user/miniconda/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/user/miniconda/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/home/user/miniconda/lib/python3.11/contextlib.py", line 155, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/gradio/route_utils.py", line 669, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    |     solved_result = await solve_dependencies(
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    |     ) = await request_body_to_args(  # body_params checked above
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 813, in request_body_to_args
    |     fields_to_extract = get_model_fields(first_field.type_)
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    |     return [
    |            ^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    |     ModelField(field_info=field_info, name=name)
    |   File "<string>", line 6, in __init__
    |   File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/_compat.py", line 109, in __post_init__
    |     self._type_adapter: TypeAdapter[Any] = TypeAdapter(
    |                                            ^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 211, in __init__
    |     core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 81, in _get_schema
    |     schema = gen.generate_schema(type_)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 490, in generate_schema
    |     schema = self._generate_schema(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    |     schema = self._generate_schema_inner(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    |     return self._annotated_schema(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1697, in _annotated_schema
    |     schema = self._apply_annotations(source_type, annotations)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1765, in _apply_annotations
    |     schema = get_inner_schema(source_type)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    |     schema = self._handler(__source_type)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1847, in new_handler
    |     schema = metadata_get_schema(source, get_inner_schema)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1843, in <lambda>
    |     lambda source, handler: handler(source)
    |                             ^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    |     schema = self._handler(__source_type)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1746, in inner_handler
    |     schema = self._generate_schema(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    |     schema = self._generate_schema_inner(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 747, in _generate_schema_inner
    |     return self.match_type(obj)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 830, in match_type
    |     return self._match_generic_type(obj, origin)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 854, in _match_generic_type
    |     return self._union_schema(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1141, in _union_schema
    |     choices.append(self.generate_schema(arg))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 490, in generate_schema
    |     schema = self._generate_schema(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    |     schema = self._generate_schema_inner(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 747, in _generate_schema_inner
    |     return self.match_type(obj)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 834, in match_type
    |     return self._unknown_type_schema(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 393, in _unknown_type_schema
    |     raise PydanticSchemaGenerationError(
    | pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
    | 
    | If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
    | 
    | For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/home/user/miniconda/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/gradio/route_utils.py", line 669, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/miniconda/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 813, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    return [
           ^
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/home/user/miniconda/lib/python3.11/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 211, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 81, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1697, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1765, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1847, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1843, in <lambda>
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1746, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 747, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 830, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 854, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1141, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 747, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 834, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 393, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

`

I've tried to backtrack and reinstall from scratch but there's nothing to do, it broke my install :(  

What can I do ??

**Comment by maepopi** [comment]
After spending a couple of hours on this I'm linking this post to this bug because when I started all over again and just cloned the repo and reran setup-docker.sh then start-docker.sh, I had the same error 

https://github.com/JarodMica/ai-voice-cloning/issues/153

Waiting for the fix then :)
