### ISSUE TITLE
start.bat issue

### ISSUE THREAD

**Issue by donc-py** [JarodMica/ai-voice-cloning#22]
Traceback (most recent call last): 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\src\[main.py](https://main.py/)", line 20, in <module> 
    from utils import * 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\src\[utils.py](https://utils.py/)", line 40, in <module> 
    from tortoise.api import TextToSpeech as TorToise_TTS, MODELS, get_model_path, pad_or_truncate 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\modules\tortoise-tts\tortoise\[api.py](https://api.py/)", line 21, in <module> 
    from tortoise.models.clvp import CLVP 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\modules\tortoise-tts\tortoise\models\[clvp.py](https://clvp.py/)", line 7, in <module> 
    from tortoise.models.transformer import Transformer 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\modules\tortoise-tts\tortoise\models\[transformer.py](https://transformer.py/)", line 6, in <module> 
    from rotary_embedding_torch import RotaryEmbedding 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\rotary_embedding_torch\__init__.py", line 1, in <module> 
    from rotary_embedding_torch.rotary_embedding_torch import apply_rotary_emb, RotaryEmbedding, broadcat, apply_learned_rotations 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py", line 10, in <module> 
    from beartype import beartype 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\__init__.py", line 57, in <module> 
    from beartype._decor.decormain import ( 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_decor\[decormain.py](https://decormain.py/)", line 23, in <module> 
    from beartype._conf.confcls import ( 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_conf\[confcls.py](https://confcls.py/)", line 25, in <module> 
    from beartype._cave._cavemap import NoneTypeOr 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_cave\_cavemap.py", line 33, in <module> 
    from beartype._util.hint.nonpep.utilnonpeptest import ( 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_util\hint\nonpep\[utilnonpeptest.py](https://utilnonpeptest.py/)", line 22, in <module> 
    from beartype._util.cache.utilcachecall import callable_cached 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_util\cache\[utilcachecall.py](https://utilcachecall.py/)", line 32, in <module> 
    from beartype._util.func.arg.utilfuncargtest import ( 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_util\func\arg\[utilfuncargtest.py](https://utilfuncargtest.py/)", line 16, in <module> 
    from beartype._util.func.arg.utilfuncargiter import ( 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_util\func\arg\[utilfuncargiter.py](https://utilfuncargiter.py/)", line 22, in <module> 
    from beartype._data.hint.datahinttyping import ( 
  File "C:\Users\USUARIO\Documents\Proyectos\AIAUDIO\ai-voice-cloning\venv\lib\site-packages\beartype\_data\hint\[datahinttyping.py](https://datahinttyping.py/)", line 142, in <module> 
    BeartypeReturn = Union[BeartypeableT, BeartypeConfedDecorator] 
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python39\lib\[typing.py](https://typing.py/)", line 243, in inner 
    return func(*args, **kwds) 
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python39\lib\[typing.py](https://typing.py/)", line 316, in getitem 
    return self._getitem(self, parameters) 
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python39\lib\[typing.py](https://typing.py/)", line 421, in Union 
    parameters = _remove_dups_flatten(parameters) 
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python39\lib\[typing.py](https://typing.py/)", line 215, in _remove_dups_flatten 
    all_params = set(params) 
TypeError: unhashable type: 'list'

**Comment by JarodMica** [comment]
This looks like a manual installation as I'm seeing a call to venv.  If you could give more info on what you did and/or you try the packaged version?

The only pointer I can say is manually run an install on the requirements.txt from the root directory.

**Comment by To1p5** [comment]
Currently facing the issue where the code is showing this when I click start.bat '
C:\Users\fmsal\Downloads\ai-voice-cloning>set PYTHONUTF8=1

C:\Users\fmsal\Downloads\ai-voice-cloning>runtime\python.exe .\src\main.py
Traceback (most recent call last):
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\src\utils.py", line 29, in <module>
    import torchaudio
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torch\_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

C:\Users\fmsal\Downloads\ai-voice-cloning>pause
Press any key to continue . . .'
I have currently have python 3.11.3 I know in the original code I believe you needed 3.9 I don't know if that could be the issue. Trying to see what I can do here to fix this.

**Comment by JarodMica** [comment]
Were you able to make any progress on this?

It's possible that during the extraction of the package, an error occurred and it extracted incomplete.  Did you get any such messages?  If so, you need to use and update 7zip before extracting it.
