### ISSUE TITLE
32/64 issue when start.bat

### ISSUE THREAD

**Issue by imp0006** [JarodMica/ai-voice-cloning#23]
C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning>set PYTHONUTF8=1

C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning>runtime\python.exe .\src\main.py
Traceback (most recent call last):
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\src\utils.py", line 45, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\rvc_pipe\rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\rvc\infer\modules\vc\modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\rvc\infer\modules\vc\utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\fairseq\__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\fairseq\scoring\__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "importlib\__init__.py", line 127, in import_module
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\fairseq\scoring\bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\fairseq\scoring\tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\sacrebleu\__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\sacrebleu\utils.py", line 9, in <module>
    import portalocker
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\portalocker\__init__.py", line 1, in <module>
    from . import __about__, constants, exceptions, portalocker, utils
  File "C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning\runtime\lib\site-packages\portalocker\portalocker.py", line 15, in <module>
    import pywintypes
  File "C:\Users\liede\AppData\Roaming\Python\Python39\site-packages\win32\lib\pywintypes.py", line 129, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\liede\AppData\Roaming\Python\Python39\site-packages\win32\lib\pywintypes.py", line 49, in __import_pywin32_system_module__
    import _win32sysloader
ImportError: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application.

C:\Users\liede\Desktop\Voice Changer Stuff\RVC Tools\ai-voice-cloning>pause
Press any key to continue . . .

I can't seem to locate the issue with the ImportError

**Comment by JarodMica** [comment]
I'm not sure why it tries to go to a local python installation here:
> File "C:\Users\liede\AppData\Roaming\Python\Python39\site-packages\win32\lib\pywintypes.py", line 129, in
import_pywin32_system_module("pywintypes", globals())
File "C:\Users\liede\AppData\Roaming\Python\Python39\site-packages\win32\lib\pywintypes.py", line 49, in import_pywin32_system_module
import _win32sysloader
ImportError: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application.

Did you run into any errors on extracting to package?
