### ISSUE TITLE
Start Errors and Issue

### ISSUE THREAD

**Issue by NightWalker77V** [JarodMica/ai-voice-cloning#25]
Hi, it's my third time downloading the file from scratch, and each time it turns back some errors. HELLPPPP!
I have i5 12th gen and Nvidia 3050 ti with 16gb Ram and 1TB Nvme

D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning>runtime\python.exe .\src\main.py
2024-01-25 02:28:39 | INFO | rvc.configs.config | No supported Nvidia GPU found
2024-01-25 02:28:39 | INFO | rvc.configs.config | Use cpu instead
Whisper detected
Traceback (most recent call last):
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\src\utils.py", line 98, in <module>
    from vall_e.emb.qnt import encode as valle_quantize
ModuleNotFoundError: No module named 'vall_e'

Traceback (most recent call last):
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\src\utils.py", line 118, in <module>
    import bark
ModuleNotFoundError: No module named 'bark'

!WARNING! Automatically deduced sample batch size returned 1.
!WARNING! Automatically deduced sample batch size returned 1.
[textbox, textbox, radio, textbox, dropdown, audio, number, slider, number, slider, slider, slider, radio, slider, slider, slider, slider, slider, slider, slider, checkboxgroup, checkbox, checkbox]
[dropdown, slider, dropdown, slider, slider, slider, slider, slider]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
!!!! WARNING !!!! No GPU available in PyTorch. You may need to reinstall PyTorch.
Loading TorToiSe... (AR: D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\models\tortoise\autoregressive.pth, diffusion: ./models/tortoise/diffusion_decoder.pth, vocoder: bigvgan_24khz_100band)
No hardware acceleration is available, falling back to CPU...
use_deepspeed api_debug False
Traceback (most recent call last):
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\utils\hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\utils\hub.py", line 485, in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=etag_timeout)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\src\main.py", line 36, in <module>
    tts = load_tts()
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\src\utils.py", line 3739, in load_tts
    tts = TorToise_TTS(minor_optimizations=not args.low_vram,
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\src\tortoise\api.py", line 298, in __init__
    self.aligner = Wav2VecAlignment(device='cpu' if get_device_name() == "dml" else self.device)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\src\tortoise\utils\wav2vec_alignment.py", line 58, in __init__
    self.model = Wav2Vec2ForCTC.from_pretrained("jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli").cpu()
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\configuration_utils.py", line 526, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning\runtime\lib\site-packages\transformers\configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load config for 'jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli' is the correct path to a directory containing a config.json file

D:\PROGRAMS\Ai voice cloning\ai-voice-cloning-v2_0\ai-voice-cloning>pause

**Comment by JarodMica** [comment]
> !!!! WARNING !!!! No GPU available in PyTorch. You may need to reinstall PyTorch.

This seems to be the issue. Can you check and ensure your Nvidia drivers are up to date?

**Comment by JarodMica** [comment]
No activity, closing for now.
