### ISSUE TITLE
Start.bat - ModuleNotFoundError: No module named 'torchaudio'

### ISSUE THREAD

**Issue by infambart** [JarodMica/ai-voice-cloning#29]
https://youtu.be/p31Ax_A5VKA?si=IzAZN9iog-ylIrAh&t=154
at this point, I get this...
(windows10, RTX3060)

***********************************************
C:\ai-voice-cloning>set PYTHONUTF8=1

C:\ai-voice-cloning>python.exe .\src\main.py
Traceback (most recent call last):
  File "C:\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "C:\ai-voice-cloning\src\utils.py", line 29, in <module>
    import torchaudio
ModuleNotFoundError: No module named 'torchaudio'

C:\ai-voice-cloning>pause
Press any key to continue . . .

**Comment by To1p5** [comment]
You got a bit further than me but I think I'm having a similar issue 
C:\Users\fmsal\Downloads\ai-voice-cloning>set PYTHONUTF8=1

C:\Users\fmsal\Downloads\ai-voice-cloning>runtime\python.exe .\src\main.py
C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\src\utils.py", line 29, in <module>
    import torchaudio
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torch\_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

C:\Users\fmsal\Downloads\ai-voice-cloning>pause
Press any key to continue . . .

**Comment by JarodMica** [comment]
> C:\ai-voice-cloning>python.exe .\src\main.py

@infambart This would suggest you did a git clone of this repo as the packaged version would call it with runtime\python.exe.  Can you double check that you downloaded the packaged version?

@To1p5 what GPU do you have? Could you try installing the latest drivers

**Comment by To1p5** [comment]
This my current gpu NVIDIA GeForce RTX 3060 Laptop GPU I'll try that now

**Comment by To1p5** [comment]
I just updated both the game drivers and the studio drivers the error did change still having issues though. It's saying it has something to do with numpy. 'C:\Users\fmsal\Downloads\ai-voice-cloning>set PYTHONUTF8=1

C:\Users\fmsal\Downloads\ai-voice-cloning>runtime\python.exe .\src\main.py
C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\src\utils.py", line 31, in <module>
    import gradio as gr
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\gradio\components.py", line 21, in <module>
    import altair as alt
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\__init__.py", line 620, in <module>
    from .vegalite import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v5 import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\vegalite\v5\__init__.py", line 2, in <module>
    from .schema import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\vegalite\v5\schema\__init__.py", line 3, in <module>
    from .core import *
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\vegalite\v5\schema\core.py", line 7, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, UndefinedType, _subclasses
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\altair\utils\core.py", line 27, in <module>
    import pandas as pd
  File "C:\Users\fmsal\Downloads\ai-voice-cloning\runtime\lib\site-packages\pandas\__init__.py", line 43, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'numpy'

C:\Users\fmsal\Downloads\ai-voice-cloning>pause
Press any key to continue . . .'


also I don't know if this means anything 'device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),'

**Comment by infambart** [comment]
@JarodMica I didn't use a git clone the 1st time, but I did have 7zip errors that I didn't recall until I just did it again.
https://huggingface.co/Jmica/ai-voice-cloning/blob/main/ai-voice-cloning-v2_0.7z
produced errors using 7zip, see attached screenshot
![Capture](https://github.com/JarodMica/ai-voice-cloning/assets/127627936/3f8b3f65-830f-491a-a8e8-9146ae2ce1f7)

**Comment by JarodMica** [comment]
This is definitely an issue, is your 7zip up to date?  I've only seen this occur with 7zip versions that needed to be updated.
