### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zafkieldark** [JarodMica/ai-voice-cloning#39]
Please help me
Traceback (most recent call last):
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\utils.py", line 45, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\rvc_pipe\rvc_infer.py", line 10, in <module>
    from rvc.infer.modules.vc.modules import VC
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\rvc\infer\modules\vc\modules.py", line 20, in <module>
    from rvc.infer.modules.vc.utils import *
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\rvc\infer\modules\vc\utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
ModuleNotFoundError: No module named 'fairseq'

**Comment by JarodMica** [comment]
This is a manual install it looks like.  I don't recommend it.

You will need to install fairseq for rvc, though the setup bat should do it for you automatically.  Do you see a fairseq wheels file in the ai voice cloning folder?

**Comment by Zafkieldark** [comment]
Hello, everything is fine, I was able to figure out what the error was and everything works.
It was necessary to reinstall transformers, and install fairseq 0.12.2 and Pytorch 2.1.
