### ISSUE TITLE
Generate audio error

### ISSUE THREAD

**Issue by Zafkieldark** [JarodMica/ai-voice-cloning#40]
Traceback (most recent call last):
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\venv\lib\site-packages\gradio\helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\webui.py", line 129, in generate_proxy
    raise e
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\webui.py", line 123, in generate_proxy
    sample, outputs, stats = generate(**kwargs)
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\utils.py", line 364, in generate
    return generate_tortoise(**kwargs)
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\utils.py", line 1229, in generate_tortoise
    settings = get_settings( override=override )
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\utils.py", line 1086, in get_settings
    settings['voice_samples'], settings['conditioning_latents'], _ = fetch_voice(voice=selected_voice)
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\src\utils.py", line 1013, in fetch_voice
    voice_samples, conditioning_latents = None, tts.get_random_conditioning_latents()
  File "D:\Work\Voice_Changer_OpenSorce\ai-voice-cloning\modules\tortoise-tts\tortoise\api.py", line 599, in get_random_conditioning_latents
    return self.rlg_auto(torch.tensor([0.0])), self.rlg_diffusion(torch.tensor([0.0]))
TypeError: 'NoneType' object is not callable

**Comment by JarodMica** [comment]
Something is not being filled which is where None is being passed.  How did you set up tortoise, are you trying to use it on a voice sample that you have provided?

**Comment by Zafkieldark** [comment]
Hagyface dont work. And all ok
