### ISSUE TITLE
eror module  No module named 'rvc_pipe'

### ISSUE THREAD

**Issue by laynz28** [JarodMica/ai-voice-cloning#45]
module error says :

/content/ai-voice-cloning
Traceback (most recent call last):
  File "/content/ai-voice-cloning/./src/main.py", line 20, in <module>
    from utils import *
  File "/content/ai-voice-cloning/src/utils.py", line 45, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
ModuleNotFoundError: No module named 'rvc_pipe'

**Comment by Mestopholis** [comment]
I'm getting the same error.  I was trying to pip install rvc_pipe, but it is not a pypi module.
Did I miss a step?
I'm running it on Ubuntu 22.04

**Comment by dzoberg** [comment]
to resolve this, clone https://github.com/JarodMica/rvc-tts-pipeline/tree/lightweight
copy the rvc_pipe folder into /ai-voice-cloning/src 
setup-cuda.sh fails to download this
