### ISSUE TITLE
Training throws error: "Something went wrong 'utf-8' codec can't decode byte 0x81 in position 51: invalid start byte"

### ISSUE THREAD

**Issue by Dioskurides** [JarodMica/ai-voice-cloning#53]
Hey i started training after preparing my dataset via the ui but it throws only errors. Ill attach my console output 

[console.txt](https://github.com/JarodMica/ai-voice-cloning/files/14336993/console.txt)

**Comment by Dioskurides** [comment]
and some other concerning stuff: 2024-02-19 23:02:00 | INFO | pytorch_lightning.utilities.migration.utils | Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.2.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint D:\ai-voice-cloning\models\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.0+cu118. Bad things might happen unless you revert torch to 1.x.
Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_voxpopuli_base_10k_asr_de.pt" to D:\ai-voice-cloning\models\torch\hub\checkpoints\wav2vec2_voxpopuli_base_10k_asr_de.pt
Loaded Whisper model
Segments sanizited:  Test.mp3

**Comment by Dioskurides** [comment]
And yet another bug: if you cheWARNING! Setting BLOOMLayerPolicy._orig_layer_class to None due to Exception: module 'transformers.models' has no attribute 'bloom'
Traceback (most recent call last):
  File "D:\ai-voice-cloning\src\main.py", line 36, in <module>
    tts = load_tts()
  File "D:\ai-voice-cloning\src\utils.py", line 3744, in load_tts
    tts = TorToise_TTS(minor_optimizations=not args.low_vram,
  File "d:\ai-voice-cloning\modules\tortoise-tts\tortoise\api.py", line 308, in __init__
    self.load_autoregressive_model(autoregressive_model_path)
  File "d:\ai-voice-cloning\modules\tortoise-tts\tortoise\api.py", line 392, in load_autoregressive_model
    self.autoregressive.post_init_gpt2_config(use_deepspeed=self.use_deepspeed, kv_cache=self.use_kv_cache)
  File "d:\ai-voice-cloning\modules\tortoise-tts\tortoise\models\autoregressive.py", line 388, in post_init_gpt2_config
    self.ds_engine = deepspeed.init_inference(model=self.inference_model,
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\__init__.py", line 288, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\inference\engine.py", line 194, in __init__
    self._apply_injection_policy(config)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\inference\engine.py", line 396, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 493, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 726, in replace_module
    replaced_module, _ = _replace_module(model, policy)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 751, in _replace_module
    _, layer_id = _replace_module(child, policies, layer_id=layer_id)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 751, in _replace_module
    _, layer_id = _replace_module(child, policies, layer_id=layer_id)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 743, in _replace_module
    replaced_module = policies[child.__class__][0](child, policies[child.__class__][-1], layer_id)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 483, in replace_fn
    new_module = replace_with_policy(child,
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\replace_module.py", line 341, in replace_with_policy
    _container.create_module()
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\module_inject\containers\gpt2.py", line 20, in create_module
    self.module = DeepSpeedGPTInference(_config, mp_group=self.mp_group)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\model_implementations\transformers\ds_gpt.py", line 20, in __init__
    super().__init__(config, mp_group, quantize_scales, quantize_groups, merge_count, mlp_extra_grouping)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\model_implementations\transformers\ds_transformer.py", line 54, in __init__
    inference_cuda_module = builder.load()
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\ops\op_builder\builder.py", line 443, in load
    self.validate_torch_version(torch_info)
  File "C:\Users\rouve\.conda\envs\clonevoice\lib\site-packages\deepspeed\ops\op_builder\builder.py", line 132, in validate_torch_version
    raise RuntimeError("PyTorch version mismatch! DeepSpeed ops were compiled and installed "
RuntimeError: PyTorch version mismatch! DeepSpeed ops were compiled and installed with a different version than what is being used at runtime. Please re-install DeepSpeed or switch torch versions. Install torch version=2.1, Runtime torch version=2.2
Drücken Sie eine beliebige Taste . . .ck use deep speed in settings the interface wont start anymore throwing a mismatch error

**Comment by chromyromer** [comment]
I have the same Problem. I trained a model without any issues, but when i tried another one, i always get this Error. Cant find any help

**Comment by Untri8ium** [comment]
Same here. I get "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 0: invalid start byte" every time I start a training. Also happens when training is halfway done. Cannot finish up
