### ISSUE TITLE
[Training] [2024-03-01T21:19:57.203746] d:\RVC\AI VOICE CLONING\ai-voice-cloning>pause

### ISSUE THREAD

**Issue by agencjamsdj** [JarodMica/ai-voice-cloning#57]
[Training] [2024-03-01T21:18:16.405114]   warnings.warn(
[Training] [2024-03-01T21:19:46.370136] Disabled distributed training.
[Training] [2024-03-01T21:19:46.370136] Loading from ./models/tortoise/dvae.pth
[Training] [2024-03-01T21:19:46.370136] Traceback (most recent call last):
[Training] [2024-03-01T21:19:46.370136]   File "d:\RVC\AI VOICE CLONING\ai-voice-cloning\src\train.py", line 72, in <module>
[Training] [2024-03-01T21:19:46.370136]     train(config_path, args.launcher)
[Training] [2024-03-01T21:19:46.370136]   File "d:\RVC\AI VOICE CLONING\ai-voice-cloning\src\train.py", line 39, in train
[Training] [2024-03-01T21:19:46.370136]     trainer.do_training()
[Training] [2024-03-01T21:19:46.370136]   File "d:\RVC\AI VOICE CLONING\ai-voice-cloning\src\dlas\train.py", line 408, in do_training
[Training] [2024-03-01T21:19:46.370136]     metric = self.do_step(train_data)
[Training] [2024-03-01T21:19:46.370136]   File "d:\RVC\AI VOICE CLONING\ai-voice-cloning\src\dlas\train.py", line 271, in do_step
[Training] [2024-03-01T21:19:46.370136]     gradient_norms_dict = self.model.optimize_parameters(
[Training] [2024-03-01T21:19:46.370136]   File "d:\RVC\AI VOICE CLONING\ai-voice-cloning\src\dlas\trainer\ExtensibleTrainer.py", line 321, in optimize_parameters
[Training] [2024-03-01T21:19:46.386620]     ns = step.do_forward_backward(
[Training] [2024-03-01T21:19:46.386620]   File "d:\RVC\AI VOICE CLONING\ai-voice-cloning\src\dlas\trainer\steps.py", line 242, in do_forward_backward
[Training] [2024-03-01T21:19:46.386620]     local_state[k] = v[grad_accum_step]
[Training] [2024-03-01T21:19:46.386620] IndexError: list index out of range
[Training] [2024-03-01T21:19:57.203746]
[Training] [2024-03-01T21:19:57.203746] d:\RVC\AI VOICE CLONING\ai-voice-cloning>pause

**Comment by AliAlWahayb** [comment]
(Batch Size) has to be divisible by (Gradient Accumulation Size)
