### ISSUE TITLE
Can't run training from Terminal (using release 2.0)

### ISSUE THREAD

**Issue by victorothon** [JarodMica/ai-voice-cloning#61]
Hi Jarod,
I've been working the past few week on training tortoise in spanish, but it has been bumpy, right now I am trying to run training as described in your last two videos on training in other languages, but it just not runing, I get this error:
```
python .\src\train.py --yaml .\training\esp\train.yaml
[2024-03-11 11:41:36,019] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "D:\StoryTellerAI\ai-voice-cloning-v2_0\ai-voice-cloning\src\train.py", line 72, in <module>
    train(config_path, args.launcher)
  File "D:\StoryTellerAI\ai-voice-cloning-v2_0\ai-voice-cloning\src\train.py", line 29, in train
    torch.cuda.set_device(opt['gpu_ids'][0])
  File "D:\StoryTellerAI\ai-voice-cloning-v2_0\ai-voice-cloning\venv\Lib\site-packages\torch\cuda\__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```
Any advice on how to solve this cuda problem, I'm running on a RTX4090, thank you

**Comment by victorothon** [comment]
Hi it turns out that the train.bat script, worked, I just ran the following:

`& .\train.bat .\training\[voice folder]\train.yaml`
