### ISSUE TITLE
Error After Running "Start.bat"

### ISSUE THREAD

**Issue by MagicalDemon10** [JarodMica/ai-voice-cloning#69]
I've tried asking google bard for fixes it told me these command:
`pip uninstall numba`
`pip install numba`

- Still after this, i get the same error when running the "start.bat"
- I've already checked that the files are intact after extracting from 7zip, and there are no missing files.
- **PLEASE Help me fix this...** 

**CPU/GPU:**
Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
NVIDIA GeForce MX130 (2GB)

**ERROR:**
```
(base) PS D:\24-AI\TTS\ai-voice-cloning> .\start.bat

D:\24-AI\TTS\ai-voice-cloning>set PYTHONUTF8=1

D:\24-AI\TTS\ai-voice-cloning>runtime\python.exe .\src\main.py
Traceback (most recent call last):
  File "D:\24-AI\TTS\ai-voice-cloning\src\main.py", line 20, in <module>
    from utils import *
  File "D:\24-AI\TTS\ai-voice-cloning\src\utils.py", line 40, in <module>
    from tortoise.api import TextToSpeech as TorToise_TTS, MODELS, get_model_path, pad_or_truncate
  File "D:\24-AI\TTS\ai-voice-cloning\src\tortoise\api.py", line 25, in <module>
    from tortoise.models.bigvgan import BigVGAN
  File "D:\24-AI\TTS\ai-voice-cloning\src\tortoise\models\bigvgan.py", line 14, in <module>
    from librosa.filters import mel as librosa_mel_fn
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "D:\24-AI\TTS\ai-voice-cloning\runtime\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

D:\24-AI\TTS\ai-voice-cloning>pause
Press any key to continue . . .
```

**Comment by MagicalDemon10** [comment]
For anyone wondering I resolved error by using these commands 
`pip uninstall numpy`
`pip install numpy==1.21.0`

Which solved the compatibility error with the project.
