### ISSUE TITLE
Bug when preparing dataset when using too many processes.

### ISSUE THREAD

**Issue by saintbrodie** [JarodMica/ai-voice-cloning#83]
UI auto sets "Processes to Use" to 112 on my system. The processing looks like it happens, but I never get the "Transcription and processing completed successfully!" message and the timer goes infinitely. 

```
Exception in thread Thread-22 (_handle_workers):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 522, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 502, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\Program Files\Python311\Lib\multiprocessing\connection.py", line 896, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\multiprocessing\connection.py", line 828, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at most 63 handles, got a sequence of length 114
```

Setting processes to 60 completes successfully.

OS: Windows 10 Pro for Workstations
Processors: Intel(R) Xeon(R) Platinum 8280L CPU @ 2.70GHz   2.69 GHz  (2 processors)
RAM: 512 GB (512 GB usable)
Video: 2x Nvidia Quadro RTX 8000

**Comment by JarodMica** [comment]
I think this looks like a limitation for multiprocessing which is what I use to parallelize the process.  I'll have to set up a limit to prevent this from happening on the repo.  Were you able to set it and run it succesfully at 64 or 63, or just 60?
