### ISSUE TITLE
Unable to train german voice

### ISSUE THREAD

**Issue by Meerfelix** [JarodMica/ai-voice-cloning#88]
I use lang code de and no function with either prepare for dataset or prepare for large data set
I am able to produce tokenzier but in final training I receive one off the following errors

I am able to train in english

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 2: invalid start byte

or

RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

I also get 'empty data set' in generation configuration tab, also it said Transcription and processing completed successfully! in prepare data set for large files.

so my general question is: do I have to prepare the program somehow before training different lang? beause this is what you seem to do in one of your videos (https://www.youtube.com/watch?v=4iqCRWdQlyE&t=449s). It is unclear to me whether this is obligatory or only your programming effort and now implemented for everyone and all lang.

kind regards and thank you

**Comment by Meerfelix** [comment]
trying to prepare dataset large file with lang code de for german

ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
Error in running whisperx for file voices\DavidNathanLargeDE\file___1.mp3: Command '['runtime\\python.exe', '-mwhisperx', WindowsPath('voices/DavidNathanLargeDE/file___1.mp3'), '--device', 'cuda', '--model', 'large-v3', '--output_dir', WindowsPath('training/DavidNathanLargeDE/processed/run/dataset/wav_splits/file___1'), '--language', 'de', '--chunk_size', '15', '--output_format', 'srt', '--no_align']' returned non-zero exit status 1.
Error processing file voices\DavidNathanLargeDE\file___1.mp3 with SRT training\DavidNathanLargeDE\processed\run\dataset\wav_splits\file___1\file___1.srt: [Errno 2] No such file or directory: 'training\\DavidNathanLargeDE\\processed\\run\\dataset\\wav_splits\\file___1\\file___1.srt'
E:\ai-voice-cloning-3.0\runtime\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")

**Comment by Gnomsons** [comment]
Same issue here!

Whisper detected
E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\components\dropdown.py:179: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py:858: UserWarning: Expected 1 arguments for function <function update_voices at 0x0000021181CED620>, received 0.
  warnings.warn(
E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\gradio\utils.py:862: UserWarning: Expected at least 1 arguments for function <function update_voices at 0x0000021181CED620>, received 0.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
2024-04-25 17:31:05 | INFO | httpx | HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
2024-04-25 17:31:05 | INFO | httpx | HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
Loading TorToiSe... (AR: None, diffusion: None, vocoder: bigvgan_24khz_100band)
Hardware acceleration found: cuda
use_deepspeed api_debug False
2024-04-25 17:31:05 | INFO | httpx | HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loading tokenizer JSON: E:\My projects\Voice\ai-voice-cloning-3.0\src\tortoise\../tortoise/data/tokenizer.json
Loaded tokenizer
Loading autoregressive model: E:\My projects\Voice\ai-voice-cloning-3.0\models\tortoise\autoregressive.pth
Loaded autoregressive model
Loaded diffusion model
Loading vocoder model: bigvgan_24khz_100band
Loading vocoder model: bigvgan_24khz_100band.pth
Removing weight norm...
Loaded vocoder model
Loaded TTS, ready for generation.
Copied ./voices\Smok-test\original_files\Smoktun.mp3 to ./voices\Smok-test\original_files\converted\Smoktun.mp3
E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\whisperx\__main__.py", line 4, in <module>
    cli()
  File "E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\whisperx\transcribe.py", line 170, in cli
    model = load_model(model_name, device=device, device_index=device_index, download_root=model_dir, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\whisperx\asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\My projects\Voice\ai-voice-cloning-3.0\runtime\Lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
Error in running whisperx for file voices\Smok-test\file___1.mp3: Command '['runtime\\python.exe', '-mwhisperx', WindowsPath('voices/Smok-test/file___1.mp3'), '--device', 'cuda', '--model', 'large-v3', '--output_dir', WindowsPath('training/Smok-test/processed/run/dataset/wav_splits/file___1'), '--language', 'ru', '--chunk_size', '15', '--output_format', 'srt']' returned non-zero exit status 1.
Error processing file voices\Smok-test\file___1.mp3 with SRT training\Smok-test\processed\run\dataset\wav_splits\file___1\file___1.srt: [Errno 2] No such file or directory: 'training\\Smok-test\\processed\\run\\dataset\\wav_splits\\file___1\\file___1.srt'

**Comment by JarodMica** [comment]
@Meerfelix and @Gnomsons, this is a GPU limitation unfortunately.  Whatever GPU you have doesn't support float16, so you won't be able to prepare your data until I can get a fix for it.

I'll have to put this on a list of things for me to fix to allow training with int8

**Comment by Meerfelix** [comment]
thank you for all your efforts! I use gtx 1080 btw.

**Comment by Meerfelix** [comment]
@JarodMica just for clarification, with an adequate GPU, it is sumptuous to prepare the data set with 'prepare large data set' and choose the according language - there is no deeper coding of language tokens required, because you already connected some databases for us?
