### ISSUE TITLE
start.bat jumps to pause and doesn't go any further

### ISSUE THREAD

**Issue by BurnedP** [JarodMica/ai-voice-cloning#9]
Hey man, thank you for putting this all together. I've played around with TortoiseTTS in the past and wanted to get back into it. Found this approach interesting and wanted to give it a try. For some reason when launching the start.bat it kinda loads but jumps to the pause statement after loading the ui link.

I know a bit of python and played around a bit. Eventually found the problem to be during the load_tts function. This took me to the utils class. In that file there a few warning, but I'd guess the problem comes from those weirdly indented lines 146 through 157. Any idea if that's where the problem comes from or if i have something set up wrong?

Also, it's kinda weird that it exits without an error and goes to the pause statement.

**Comment by JarodMica** [comment]
> Hey man, thank you for putting this all together. I've played around with TortoiseTTS in the past and wanted to get back into it. Found this approach interesting and wanted to give it a try. For some reason when launching the start.bat it kinda loads but jumps to the pause statement after loading the ui link.
> 
> I know a bit of python and played around a bit. Eventually found the problem to be during the load_tts function. This took me to the utils class. In that file there a few warning, but I'd guess the problem comes from those weirdly indented lines 146 through 157. Any idea if that's where the problem comes from or if i have something set up wrong?
> 
> Also, it's kinda weird that it exits without an error and goes to the pause statement.

That looks like the Bark instantiation, which should fail out for bark and vall-e, but it shouldn't end the script.  Could you copy and paste/ screenshot the terminal after it fails?

Also, what GPU and operating system do you have?

**Comment by BurnedP** [comment]
> That looks like the Bark instantiation, which should fail out for bark and vall-e, but it shouldn't end the script. Could you copy and paste/ screenshot the terminal after it fails?
> 
> Also, what GPU and operating system do you have?

For sure. Her goes the terminal:
```
C:\Tools\TortoiseTTS>set PYTHONUTF8=1

C:\Tools\TortoiseTTS>runtime\python.exe .\src\main.py
Whisper detected
Traceback (most recent call last):
  File "C:\Tools\TortoiseTTS\src\utils.py", line 98, in <module>
    from vall_e.emb.qnt import encode as valle_quantize
ModuleNotFoundError: No module named 'vall_e'

Traceback (most recent call last):
  File "C:\Tools\TortoiseTTS\src\utils.py", line 118, in <module>
    import bark
ModuleNotFoundError: No module named 'bark'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading TorToiSe... (AR: None, diffusion: None, vocoder: bigvgan_24khz_100band)
Hardware acceleration found: cuda
use_deepspeed api_debug False

C:\Tools\TortoiseTTS>pause
Press any key to continue . . .
```

For specs, I have an rtx 3070 and windows 11. I deleted all other python installations in case they were conflicting and only got 3.9.11 installed. Maybe you could throw me the pip list and see if installed packages are the same versions?

**Comment by JarodMica** [comment]
> > That looks like the Bark instantiation, which should fail out for bark and vall-e, but it shouldn't end the script. Could you copy and paste/ screenshot the terminal after it fails?
> > Also, what GPU and operating system do you have?
> 
> For sure. Her goes the terminal:
> 
> ```
> C:\Tools\TortoiseTTS>set PYTHONUTF8=1
> 
> C:\Tools\TortoiseTTS>runtime\python.exe .\src\main.py
> Whisper detected
> Traceback (most recent call last):
>   File "C:\Tools\TortoiseTTS\src\utils.py", line 98, in <module>
>     from vall_e.emb.qnt import encode as valle_quantize
> ModuleNotFoundError: No module named 'vall_e'
> 
> Traceback (most recent call last):
>   File "C:\Tools\TortoiseTTS\src\utils.py", line 118, in <module>
>     import bark
> ModuleNotFoundError: No module named 'bark'
> 
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> Loading TorToiSe... (AR: None, diffusion: None, vocoder: bigvgan_24khz_100band)
> Hardware acceleration found: cuda
> use_deepspeed api_debug False
> 
> C:\Tools\TortoiseTTS>pause
> Press any key to continue . . .
> ```
> 
> For specs, I have an rtx 3070 and windows 11. I deleted all other python installations in case they were conflicting and only got 3.9.11 installed. Maybe you could throw me the pip list and see if installed packages are the same versions?

Interesting, there's nothing to go off with that, but usually after deepspeed it starts trying to load in the models which means for some reason, loading the models is causing issues.

Could you check to make sure your 7zip is up-to-date and if it isn't, then you may need to re-extract the package.

Since you do have experience with python, if the package doesn't work for you, you could run a manual installation which in this case, you could follow the video here: https://youtu.be/6sTsqSQYIzs?si=Q0F7FPYwWDTgdZ1Z

There shouldn't be any reason to run a pip list because all of the packages are frozen inside of runtime, along with the python version. Usually there'd also be some type of module not found or function/class not found error if that was the case.  I'm out of town for about a week so can't do much on my end rn!

**Comment by BurnedP** [comment]
> Interesting, there's nothing to go off with that, but usually after deepspeed it starts trying to load in the models which means for some reason, loading the models is causing issues.
> 
> Could you check to make sure your 7zip is up-to-date and if it isn't, then you may need to re-extract the package.
> 
> Since you do have experience with python, if the package doesn't work for you, you could run a manual installation which in this case, you could follow the video here: https://youtu.be/6sTsqSQYIzs?si=Q0F7FPYwWDTgdZ1Z
> 
> There shouldn't be any reason to run a pip list because all of the packages are frozen inside of runtime, along with the python version. Usually there'd also be some type of module not found or function/class not found error if that was the case. I'm out of town for about a week so can't do much on my end rn!

Agreed, it's really weird. No error, nothing. Thanks for the quick responses btw, you're incredible. I updated 1zip and am downloading the file again, this time through my browser. Previously downloaded it through hf python library as it has given me better speed in the past. Could it be that? I'll see what I can dig up if it doesn't work anymore. Enjoy your time away! Big thanks for your help man

**Comment by BurnedP** [comment]
Same thing seems to be happening, no clue what's going on. Will investigate a bit further and try to understand what breaks.

**Comment by JarodMica** [comment]
> > Interesting, there's nothing to go off with that, but usually after deepspeed it starts trying to load in the models which means for some reason, loading the models is causing issues.
> > Could you check to make sure your 7zip is up-to-date and if it isn't, then you may need to re-extract the package.
> > Since you do have experience with python, if the package doesn't work for you, you could run a manual installation which in this case, you could follow the video here: https://youtu.be/6sTsqSQYIzs?si=Q0F7FPYwWDTgdZ1Z
> > There shouldn't be any reason to run a pip list because all of the packages are frozen inside of runtime, along with the python version. Usually there'd also be some type of module not found or function/class not found error if that was the case. I'm out of town for about a week so can't do much on my end rn!
> 
> Agreed, it's really weird. No error, nothing. Thanks for the quick responses btw, you're incredible. I updated 1zip and am downloading the file again, this time through my browser. Previously downloaded it through hf python library as it has given me better speed in the past. Could it be that? I'll see what I can dig up if it doesn't work anymore. Enjoy your time away! Big thanks for your help man

Np, just caught me on a free morning :)!

It is possible something could've gone astray there, but I don't think zips can be extracted if not fully downloaded. Regardless, I think updating the 7zip should help and then running through the browser for *extra* precaution.

Thanks and wish ya luck on it, update the thread on what occurs!

**Comment by BurnedP** [comment]
So, updated 7zip and downloaded the package through the browser, same problem as before. No clue what's going on. Will probe a little bit further and try to understand what is breaking, otherwise I'll try the older method, but if I'm correct it lacks deepspeed and hifigan, right?

I'll keep you updated if I find anything, cheers!

**Comment by JarodMica** [comment]
> So, updated 7zip and downloaded the package through the browser, same problem as before. No clue what's going on. Will probe a little bit further and try to understand what is breaking, otherwise I'll try the older method, but if I'm correct it lacks deepspeed and hifigan, right?
> 
> I'll keep you updated if I find anything, cheers!

You can git clone my repository and it works instead of using the older one. Then run the setupcuda bat and it'll function the same

**Comment by BurnedP** [comment]
> > So, updated 7zip and downloaded the package through the browser, same problem as before. No clue what's going on. Will probe a little bit further and try to understand what is breaking, otherwise I'll try the older method, but if I'm correct it lacks deepspeed and hifigan, right?
> > I'll keep you updated if I find anything, cheers!
> 
> You can git clone my repository and it works instead of using the older one. Then run the setupcuda bat and it'll function the same

And that worked. I'm not sure what stops working when downloading the whole package rather than doing it manually. Still downloading models, but it went past the stage where it would hang. I'll keep everyone updated and, if I have time, I might even automate the whole process to make it a one click install.

Thank you Jarod for all the help. Keep making great content!

PS: I won't close the issue as the original problem was not resolved, but rather got it working through different means. Still, feel free to mark it as closed if you so choose.

**Comment by BurnedP** [comment]
Hey Jarod, just leaving this here for other people to see as well as close the topic with it. Did a git pull and kept getting an error for rvc_pipe not installed. Missing module, guess it's something you custom made. Anyway, decided to give the "release" method another try and, lo and behold, it works like a charm out of the box. I'd consider the problem fixes, thus I'll close th bug. THank you for all your work and for all the help you provided earlier!
